### ISSUE TITLE
Tests fails with Node v17.8.0

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-storage#6]
```
FAIL   node:integration  test/integration/fdp-class.spec.ts
  ● Test suite failed to run

    error:0308010C:digital envelope routines::unsupported

      18 |  */
      19 | export function generateUser(): TestUser {
    > 20 |   const wallet = Wallet.createRandom()
         |                         ^
      21 |
      22 |   return {
      23 |     username: crypto.randomBytes(USERNAME_LENGTH).toString('hex'),

      at ripemd160 (node_modules/@ethersproject/sha2/src.ts/sha2.ts:14:29)
      at new HDNode (node_modules/@ethersproject/hdnode/src.ts/index.ts:117:67)
      at Function.Object.<anonymous>.HDNode._fromSeed (node_modules/@ethersproject/hdnode/src.ts/index.ts:260:16)
      at Function.Object.<anonymous>.HDNode.fromMnemonic (node_modules/@ethersproject/hdnode/src.ts/index.ts:271:23)
      at Function.Object.<anonymous>.Wallet.fromMnemonic (node_modules/@ethersproject/wallet/src.ts/index.ts:194:34)
      at Function.createRandom (node_modules/@ethersproject/wallet/src.ts/index.ts:179:23)
      at generateUser (test/utils.ts:20:25)
      at test/integration/fdp-class.spec.ts:18:12
```

**Comment by crtahlin** [comment]
This seems done, was it resolved @IgorShadurin ?

**Comment by IgorShadurin** [comment]
> This seems done, was it resolved @IgorShadurin ?

It is not done. We are still waiting node 17 LTS.

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-storage/6?planning-poker) with ZenHub @IgorShadurin @nugaon

**Comment by IgorShadurin** [comment]
node 18 works good
